# -*- coding: utf-8 -*-
"""cursobasicopython.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VzNJe_29-E0hvRwLXfaIxyic3seYHdK7

passo a passo  da solução do desafio
"""

from re import L
# logica de progamação

# passo 1 percorrer todos os rquivos da pasta base de dados(pasta vendas)
import os
import pandas as pd
import plotly.express as px

lista_arquivo = os.listdir('/content/drive/MyDrive/vendas/Vendas')

print(lista_arquivo)
for arquivo in lista_arquivo:
  print(arquivo)

tabela_total = pd.DataFrame()

# passo 2 importar as base de dados de vendas
for arquivo in lista_arquivo:
# se tem 'vendas' no nome do arquivo, então
 if 'Vendas' in arquivo:
   print(arquivo)
  #importa o arquivo
   tabela = pd.read_csv(f'/content/drive/MyDrive/vendas/Vendas/{arquivo}')
   tabela_total = tabela_total.append(tabela)
   
  
# passo 3 trata e /compilar as bases de dados
display(tabela_total)

# passo 4 calcular o produto mais vendido (quantidade)
tabela_produtos = tabela_total.groupby('Produto').sum()
tabela_produtos = tabela_produtos [['Quantidade Vendida' , 'Preco Unitario']] .sort_values(by = 'Quantidade Vendida', ascending=False)
display(tabela_produtos)

# passo 5 calcular o produto que mais faturou (faturamneto)
tabela_total['Faturamento'] = tabela_total['Quantidade Vendida'] * tabela_total['Preco Unitario']
tabela_faturamneto = tabela_total.groupby('Produto').sum()
tabela_faturamneto = tabela_faturamneto [['Faturamento' , ]] .sort_values(by = 'Faturamento', ascending=False)
display(tabela_faturamneto)

# passo 6 calcular loja/cidade que mais vendeu (faturamento) criar um grafico/deshboard

tabela_lojas = tabela_total.groupby('Loja').sum()
tabela_lojas = tabela_lojas[['Faturamento',]] .sort_values(by = 'Loja', ascending=False)
display(tabela_lojas)

grafico = px.bar (tabela_lojas, x=tabela_lojas.index, y='Faturamento')
grafico.show